version: "3.9"
services:
  sentiment-analysis:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    logging:
      driver: "none"
